<?php

namespace WebImage\ServiceManager;

use WebImage\Container\Container;

class ServiceManager extends Container implements ServiceManagerInterface {
	/**
	 * ServiceManager constructor.
	 * @param ServiceManagerConfigInterface|null $config
	 */
	public function __construct(ServiceManagerConfigInterface $config=null)
	{
		parent::__construct();
		$config->configureServiceManager($this);
	}

	public function get($id)
	{
		$instance = parent::get($id); // TODO: Change the autogenerated stub

		if ($instance instanceof ServiceManagerAwareInterface) {
			$instance->setServiceManager($this);
		}

		return $instance;
	}

}